version: "3"

services:
  db_postgres:
    image: postgres:12.9
    environment:
      - POSTGRES_DB=puppy_hero
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django_app:
    build: .
    environment:
      - DB_HOST=db_postgres
      - DB_NAME=puppy_hero
      - DB_USER=postgres
      - DB_PASSWORD=123456
    volumes:
      - .:/code
      - static:/code/static
    depends_on:
      - db_postgres

  nginx:
    image: nginx:1.20
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/static
    depends_on:
      - django_app


volumes:
  .:
  postgres_data:
  static:
