version: "3"

services:
  db_postgress:

    image: postgres:12.9
    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment:
        - POSTGRES_PASSWORD=123456
        - POSTGRES_USER=postgres
        - POSTGRES_DB=puppy_hero
    ports:
      - 5432

  django_app:

    build: .
    environment:
      - DB_HOST=db_postgres
      - DB_NAME=django_app
      - DB_USER=puppy_hero
      - DB_PASSWORD=123456
    volumes:
      - static:/code/static
      - media:/code/albergue_mascotas/media
      - perfil:/code/albergue_mascotas/media/perfil
      - .:/code

    depends_on:
      - db_postgress
      
    expose:
      - 8000
    restart: always


  nginx:

    image: nginx:1.18.0
    ports:
      - 8000:80

    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/static

volumes:

  .:
  postgres_data:
  static:
  media:
  perfil:
