version: "3"

services:
  db_postgress:
    image: postgres:12.9
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: 123456

  django_app:
    build: .
    volumes:
      - static:/code/static
      - .:/code

    depends_on:
      - db_postgress


  nginx:
    image: nginx:1.18.0
    ports:
      - 8000:80

    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/staticZ

volumes:
  .:
  postgres_data:
  static:
