version: '3.9'

services:
  db:
    image: postgres:12
    volumes:
      - ./data/db:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=puppy_heroe
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=123456

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Albergue_mascotas
    ports:
      - '8000:8000'
    depends_on:
      - db
