version: '3.4'

services:
  0980proyectosalberguedemascotas:
    image: 0980proyectosalberguedemascotas
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
