# Generated by Django 4.0.3 on 2022-04-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina1app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud_adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.PositiveIntegerField(max_length=8)),
                ('domicilio', models.CharField(max_length=1000)),
                ('id_mascota', models.PositiveIntegerField()),
                ('razon', models.TextField()),
            ],
        ),
    ]
