# Generated by Django 4.0.3 on 2022-04-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina1app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_mascota',
            name='foto_mascota',
            field=models.ImageField(upload_to='fotos_mascotas'),
        ),
    ]
