# Generated by Django 4.0.3 on 2022-04-13 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina1app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_mascota',
            name='foto_mascota',
        ),
    ]
