# Generated by Django 4.0.3 on 2022-04-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina1app', '0002_solicitud_adopcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_adopcion',
            name='telefono',
            field=models.PositiveIntegerField(),
        ),
    ]
