# Generated by Django 4.0.3 on 2022-04-13 01:22

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pagina1app', '0002_alter_registro_mascota_foto_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_mascota',
            name='edad_mascota',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='registro_mascota',
            name='fecha_rescate_mascota',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='registro_mascota',
            name='fecha_vacuna_mascota',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='registro_mascota',
            name='foto_mascota',
            field=models.ImageField(null=True, upload_to='fotos_mascotas'),
        ),
        migrations.AlterField(
            model_name='registro_mascota',
            name='nombre_mascota',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registro_mascota',
            name='raza_mascota',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='registro_mascota',
            name='sexo_mascota',
            field=models.IntegerField(choices=[[0, 'Macho'], [1, 'Hembra']], null=True),
        ),
        migrations.AlterField(
            model_name='registro_mascota',
            name='vacunas_mascota',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('rabia', 'Rabia'), ('distemper', 'Distemper'), ('leptospirosis', 'Leptospirosis'), ('hepatitis_canina', 'Hepatitis canina'), ('parainfluenza', 'Parainfluenza')], max_length=60, null=True),
        ),
    ]
