# Generated by Django 4.0.3 on 2022-04-17 07:28

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pagina1app', '0003_alter_solicitud_adopcion_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_mascota',
            name='id',
        ),
        migrations.AlterField(
            model_name='registro_mascota',
            name='fecha_rescate_mascota',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registro_mascota',
            name='fecha_vacuna_mascota',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registro_mascota',
            name='foto_mascota',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_mascotas'),
        ),
        migrations.AlterField(
            model_name='registro_mascota',
            name='id_mascota',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registro_mascota',
            name='vacunas_mascota',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('rabia', 'Rabia'), ('distemper', 'Distemper'), ('leptospirosis', 'Leptospirosis'), ('hepatitis_canina', 'Hepatitis canina'), ('parainfluenza', 'Parainfluenza')], max_length=60, null=True),
        ),
    ]
