# Generated by Django 4.0.3 on 2022-04-17 08:01

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pagina1app', '0004_remove_registro_mascota_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_mascota',
            name='foto_mascota',
            field=models.ImageField(null=True, upload_to='fotos_mascotas'),
        ),
        migrations.AlterField(
            model_name='registro_mascota',
            name='vacunas_mascota',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('rabia', 'Rabia'), ('distemper', 'Distemper'), ('leptospirosis', 'Leptospirosis'), ('hepatitis_canina', 'Hepatitis canina'), ('parainfluenza', 'Parainfluenza')], max_length=60),
        ),
    ]
