# Generated by Django 4.0.3 on 2022-04-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina1app', '0004_foto_mascota_remove_registro_mascota_foto_mascota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto_mascota',
            name='foto_mascota',
            field=models.ImageField(null=True, upload_to='fotos_mascotas'),
        ),
    ]
