# Generated by Django 4.0.3 on 2022-04-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina1app', '0005_alter_foto_mascota_foto_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto_mascota',
            name='foto_mascota',
            field=models.ImageField(blank=True, upload_to='media_formularios/fotos_mascotas'),
        ),
    ]
